<template>
    <main>

    	<!--? BIENVENIDOS -->
        <div class="section-bienvenidos">
            <div class="slider-height2 d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12 pt-4 mt-3 mb-3">
                            <h2 class="mb-4 pl-4 font-weight-bold">EXPO VIRTUAL</h2>
                           	<p class="pl-4 pt-2">¡Bienvenido!</p>
                           	<div><p class="pl-4 float-left">Presione sobre cada stand para acceder al contenido de cada expositor en el símbolo</p> <img src="~/assets/img/buttons/stand.png" width="60px" class="float-left pl-4"></div>
                            <div class="">
                             <p class="float-left pl-4 pt-2">Para ingresar a las Conferencias y Simposium de las Jornadas Virtuales presione el símbolo</p>
                             <img src="~/assets/img/buttons/video.png" width="60px" class="float-left pl-4">
                             </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="alert alert-dark d-block d-sm-none text-center aviso-pantalla m-0" role="alert">
          <img src="~/assets/img/buttons/gira_pantalla.png" width="px" class="float-left p-3 m-3">
          <p class="text-left">En dispositivos moviles le recomendamos mantener la vista  horizontal de su pantalla.</p>
        </div>
        <!-- BIENVENIDOS END -->

        <div>
            <!-- Image Map Generated by http://www.image-map.net/ -->
            <div style="position:relative"><img id="main-image" src="~/assets/images/panoramica.jpg" width="100%">
                <a href="/congreso-virtual/live" class="rim-hotspot" style="width:10.1%; height:31.2%; left:87.8%; top:38.4%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
                <a href="/congreso-virtual/prolia" class="rim-hotspot" style="width:8.6%; height:16.7%; left:78.2%; top:55.8%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
                <a href="/congreso-virtual/italmex" class="rim-hotspot" style="width:8.6%; height:16.5%; left:68.7%; top:55.6%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
                <a href="/congreso-virtual/lilly" class="rim-hotspot" style="width:9.4%; height:14.2%; left:58.0%; top:56.1%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
                <a href="/congreso-virtual/medix" class="rim-hotspot" style="width:8.3%; height:16.2%; left:48.2%; top:55.0%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
                <a href="/congreso-virtual/m8" class="rim-hotspot" style="width:9.0%; height:16.2%; left:37.0%; top:54.5%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
                <a href="/congreso-virtual/ammom" class="rim-hotspot" style="width:9.1%; height:18.2%; left:26.8%; top:53.8%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
                <a href="/congreso-virtual/asofarma" class="rim-hotspot" style="width:10.4%; height:18.6%; left:15.6%; top:53.8%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
                <a href="/congreso-virtual/live" class="rim-hotspot" style="width:10.7%; height:31.5%; left:0.8%; top:37.6%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
               <!--<a @click="$bvModal.show('uno')" class="rim-hotspot" style="width:10.1%; height:31.2%; left:87.8%; top:38.4%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
                <a @click="$bvModal.show('uno')" class="rim-hotspot" style="width:8.6%; height:16.7%; left:78.2%; top:55.8%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
                <a @click="$bvModal.show('uno')" class="rim-hotspot" style="width:8.6%; height:16.5%; left:68.7%; top:55.6%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
                <a @click="$bvModal.show('uno')" class="rim-hotspot" style="width:9.4%; height:14.2%; left:58.0%; top:56.1%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
                <a @click="$bvModal.show('uno')" class="rim-hotspot" style="width:8.3%; height:16.2%; left:48.2%; top:55.0%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
                <a @click="$bvModal.show('uno')" class="rim-hotspot" style="width:9.0%; height:16.2%; left:37.0%; top:54.5%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
                <a @click="$bvModal.show('uno')" class="rim-hotspot" style="width:9.1%; height:18.2%; left:26.8%; top:53.8%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
                <a @click="$bvModal.show('uno')" class="rim-hotspot" style="width:10.4%; height:18.6%; left:15.6%; top:53.8%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>
                <a @click="$bvModal.show('uno')" class="rim-hotspot" style="width:10.7%; height:31.5%; left:0.8%; top:37.6%; position:absolute; cursor:pointer; display:block; z-index:5; overflow:hidden;"></a>-->
            </div>
        </div>
        <b-modal  id="uno" hide-footer>
            <div class="d-block text-center">
                <h2 class="p-4">Disponible a partir del 23 de Octubre.</h2>
            </div>
        </b-modal>

     </main>

</template>


<script>
  export default {
    name: "index",
    middleware: ['authenticated']
  }
</script>

<style lang="scss" scoped>
    @import "assets/scss/color";
    
    .section-bienvenidos{
    	background: linear-gradient(to bottom, #7609f3,#9c12db);
    	height:auto;
    	h2 , p{
    		color:white;
    		font-weight:lighter;
    	}
    }
    .slider-height2{
    	height:auto;
    }
    .aviso-pantalla{
      background-color:#7D4199!important;
      padding:30px 10px 30px 10px;
      p{
        color:white;
      }
    }


    .contact-info {
        a {
            color: $theme-color;
        }
    }
</style>
